const fs = require('fs');
const lines = [];
lines.push('"use client";');
lines.push('');
lines.push('import { useEffect, useState } from "react";');
lines.push('import Link from "next/link";');
lines.push('import { usePathname } from "next/navigation";');
lines.push('import Image from "next/image";');
lines.push('import { motion, AnimatePresence } from "framer-motion";');
lines.push('import { Menu, X, ChevronRight, Phone, Diamond } from "lucide-react";');
lines.push('import { NAV_LINKS, SITE_CONFIG, CONTACT_INFO } from "@/lib/constants";');
lines.push('import { cn } from "@/lib/utils";');
lines.push('');
lines.push('export default function Navbar() {');
lines.push('  const [scrolled, setScrolled] = useState(false);');
lines.push('  const [mobileOpen, setMobileOpen] = useState(false);');
lines.push('  const pathname = usePathname();');
lines.push('');
lines.push('  useEffect(() => {');
lines.push('    const onScroll = () => setScrolled(window.scrollY > 50);');
lines.push('    window.addEventListener("scroll", onScroll, { passive: true });');
lines.push('    onScroll();');
lines.push('    return () => window.removeEventListener("scroll", onScroll);');
lines.push('  }, []);');
lines.push('');
lines.push('  useEffect(() => { setMobileOpen(false); }, [pathname]);');
lines.push('');
lines.push('  useEffect(() => {');
lines.push('    document.body.style.overflow = mobileOpen ? "hidden" : "";');
lines.push('    return () => { document.body.style.overflow = ""; };');
lines.push('  }, [mobileOpen]);');
lines.push('');
lines.push('  const isActive = (href: string) =>');
lines.push('    href === "/" ? pathname === "/" : pathname.startsWith(href);');
fs.writeFileSync('.ztmp/nav_p1.txt', lines.join('\n'));
console.log('p1 done');
